### ISSUE TITLE
Docker build fails on OSX

### ISSUE THREAD

**Issue by adrianbrink** [redox-os/redox#1037]
**Reproduction**: Follow the steps in the docker/ on OSX.

**Expected behavior**: README steps work

**Actual behavior**: Error

Run this on OSX.
```
docker build --build-arg LOCAL_UID="$(id -u)" --build-arg LOCAL_GID="$(id -g)" \
    -t redox docker/
```

Output:
```
The following NEW packages will be installed:
  x86-64-unknown-redox-binutils x86-64-unknown-redox-gcc
  x86-64-unknown-redox-newlib
0 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
Need to get 33.5 MB of archives.
After this operation, 157 MB of additional disk space will be used.
Get:1 https://static.redox-os.org/toolchain/apt  x86-64-unknown-redox-binutils 0.0.1build611 [2165 kB]
Get:2 https://static.redox-os.org/toolchain/apt  x86-64-unknown-redox-newlib 0.0.2build611 [478 kB]
Get:3 https://static.redox-os.org/toolchain/apt  x86-64-unknown-redox-gcc 0.0.1build611 [30.8 MB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 33.5 MB in 22s (1467 kB/s)
Selecting previously unselected package x86-64-unknown-redox-binutils.
(Reading database ... 16679 files and directories currently installed.)
Preparing to unpack .../x86-64-unknown-redox-binutils_0.0.1build611_amd64.deb ...
Unpacking x86-64-unknown-redox-binutils (0.0.1build611) ...
Selecting previously unselected package x86-64-unknown-redox-newlib.
Preparing to unpack .../x86-64-unknown-redox-newlib_0.0.2build611_amd64.deb ...
Unpacking x86-64-unknown-redox-newlib (0.0.2build611) ...
Selecting previously unselected package x86-64-unknown-redox-gcc.
Preparing to unpack .../x86-64-unknown-redox-gcc_0.0.1build611_amd64.deb ...
Unpacking x86-64-unknown-redox-gcc (0.0.1build611) ...
Processing triggers for libc-bin (2.24-9ubuntu2.2) ...
Setting up x86-64-unknown-redox-newlib (0.0.2build611) ...
Setting up x86-64-unknown-redox-binutils (0.0.1build611) ...
Setting up x86-64-unknown-redox-gcc (0.0.1build611) ...
Processing triggers for libc-bin (2.24-9ubuntu2.2) ...
groupadd: GID '20' already exists
The command '/bin/sh -c apt-get update       && apt-get install -y dirmngr git gosu gcc fuse nasm qemu-utils pkg-config              libfuse-dev make curl wget file sudo apt-transport-https autoconf flex              bison texinfo       && apt-key adv --keyserver keyserver.ubuntu.com --recv-keys AA12E97F0881517F       && echo "deb https://static.redox-os.org/toolchain/apt/ /" >> /etc/apt/sources.list.d/redox.list       && apt-get update -o Dir::Etc::sourcelist="redox.list"       && apt-get install -y x86-64-unknown-redox-newlib x86-64-unknown-redox-binutils x86-64-unknown-redox-gcc       && groupadd -g $BUILD_GID user       && useradd --shell /bin/bash -u $BUILD_UID -g $BUILD_GID -o -c "" -m $USER       && echo "$USER ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/user-no-sudo-password' returned a non-zero code: 4
```

Output of
```
id -g => 20
id -u => 501
```

Any help on how to get Redox to build on OSX would be appreciated.

**Comment by fengalin** [comment]
According to [this thread](https://stackoverflow.com/questions/43097341/docker-on-macosx-does-not-translate-file-ownership-correctly-in-volumes), the `uid` / `gid` mechanism we use for linux is not necessary for macos. I don't have a mac to test. Could you try the following modifications. If it works, I think we should be able to implement a solution for both systems.

### Get/Update the submodules
Do this before modifying the files otherwise git will complain about local modifications.
```
git pull --rebase --recurse-submodules && git submodule sync \
    && git submodule update --recursive --init
```
### Files to modify
#### Dockerfile
```
FROM ubuntu:17.04

ENV USER user
RUN   apt-get update \
      && apt-get install -y dirmngr git gosu gcc fuse nasm qemu-utils pkg-config \
             libfuse-dev make curl wget file sudo apt-transport-https autoconf flex \
             bison texinfo \
      && apt-key adv --keyserver keyserver.ubuntu.com --recv-keys AA12E97F0881517F \
      && echo "deb https://static.redox-os.org/toolchain/apt/ /" >> /etc/apt/sources.list.d/redox.list \
      && apt-get update -o Dir::Etc::sourcelist="redox.list" \
      && apt-get install -y x86-64-unknown-redox-newlib x86-64-unknown-redox-binutils x86-64-unknown-redox-gcc \
      && useradd --shell /bin/bash -c "" -m $USER \
      && echo "$USER ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/user-no-sudo-password

COPY entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

USER $USER
ENV HOME /home/$USER
ENV PATH $HOME/.cargo/bin:$PATH
ENV SRC_PATH $HOME/src
WORKDIR $HOME
RUN   curl https://sh.rustup.rs > sh.rustup.rs \
      && sh sh.rustup.rs -y \
      && rustup update \
      && rustup component add rust-src \
      && rustup default nightly \
      && curl -O https://ftp.gnu.org/gnu/automake/automake-1.15.1.tar.gz \
      && tar -xvpf automake-1.15.1.tar.gz; cd automake-1.15.1; ./configure; make; sudo make install; cd .. \
      && cargo install xargo \
      && cargo install cargo-config \
      && mkdir -p $SRC_PATH

WORKDIR $SRC_PATH
USER root

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
```

#### entrypoint.sh
```
#!/usr/bin/env bash
exec gosu user:user "$@"
```

### Then use these commands
#### Build the container
```
docker build -t redox docker/
```
#### Build Redox
```
docker run --cap-add MKNOD --cap-add SYS_ADMIN \
    --device /dev/fuse -v "$(pwd):/home/user/src" --rm redox make fetch all
```

**Comment by adrianbrink** [comment]
The first step fixes building the container. 

I'm trying the second step right now.

**Comment by adrianbrink** [comment]
What's the expected output though? Now it is just at `Running ....` and nothing else.

Shouldn't a window open with redox?

**Comment by adrianbrink** [comment]
It works, but it takes forever. Do I need to run the `build redox` step every time?

**Comment by fengalin** [comment]
Are you getting `Running...` from the build command? You should see compiler outputs.
Once redox is built, you will use `make qemu` to launch the OS. Of course, you won't need to rebuild it every time.

**Comment by fengalin** [comment]
I meant: the command starting with `docker run..`

**Comment by adrianbrink** [comment]
It took probably a good hour to build (on mac book pro 13" 2015), but it finally runs
I don't think that audio works, but I have a window.

@fengalin How can I submit this as a PR? I guess I can't take it the id stuff completely.

**Comment by fengalin** [comment]
I'm working on a solution based on our discussion to handle Linux and MacOS. I'll submit a PR when [this one](https://github.com/redox-os/redox/pull/1035) is merged. Meanwhile, since I can't test on MacOS, could you please test what I intend to submit? (See the last part if you don't want to go through a full build just now).

Proceed as follow:
1. Remove your previous redox container.
2. `git clone -b docker_linux_macos https://github.com/fengalin/redox.git ; cd redox`
3. `docker build -t redox docker/`
4. `git pull --rebase --recurse-submodules && git submodule sync && git submodule update --recursive --init`
5. `docker run --cap-add MKNOD --cap-add SYS_ADMIN --device /dev/fuse -v "$(pwd):/home/user/src" --rm redox make fetch all`

If you don't want to rebuild everything just now, remove `all` from the last command, so it reads:
`docker run --cap-add MKNOD --cap-add SYS_ADMIN --device /dev/fuse -v "$(pwd):/home/user/src" --rm redox make fetch`

This should take a couple of minutes and should be good enough to validate the modifications.

**Comment by adrianbrink** [comment]
It works :-) It allows me to build and run redox using docker and qemy

**Comment by fengalin** [comment]
Great! Thank you! I've updated the README on my branch. I'll submit a PR when the one on the security modules is merged.
