### ISSUE TITLE
Redox's interface cs should be based on wayland and the like, NOT xorg!

### ISSUE THREAD

**Issue by sackery** [redox-os/redox#130]

**Comment by hauleth** [comment]
That was discussed earlier and everyone agreed.

**Comment by mgattozzi** [comment]
X is aging and wayland being supported would be preferable. As @hauleth said this was already discussed. I suggest this issue be closed then one be opened regarding who wants to code it etc.

**Comment by bubnenkoff** [comment]
Do you mean Wayland-like protocol, or porting Wayland to redox?

**Comment by stratact** [comment]
Sigh, what *specifically* is wrong with the windowing system, Orbital? Everything is done from scratch, we take great ideas and throw away not so great ones. This is how the whole project evolves. Just because it took some ideas from X11, doesn't mean it's going to be a full Rust reimplementation of it. It's our own windowing system, not xorg's or wayland's.

So, please, give us specifics about what you don't want to see, that X11 has, other than its problem of 30 years of API bulk up.

And honestly, I know some people will actually miss the remote display capabilities that X11 has, but will not exist in Wayland, because of its design. So there is merit at looking both sides.

**Comment by jackpot51** [comment]
It is a custom design that is closer to wayland in layout, this is already taken care of
