### ISSUE TITLE
Porting compilers of other languages and software ro Redox?

### ISSUE THREAD

**Issue by bubnenkoff** [redox-os/redox#137]
I am interesting in developing Redox, but I do not know Rust and prefer to write code in D. And I think it's much easier then Rust for user-apps.
Would it be hard to port D (DMD/LDC/SDC) compiler to Redox? Is it's hard task?
What about languages like Python and Nim?

Also question about software. Redox look like totally different OS, and have not posix compatibility (and I think it's cool), but would it be possible to post any existent software to Redox? Which difficulty with it would be?

**Comment by stratact** [comment]
Along the way, Redox could support other languages, like any other operating system would. So I don't see how that will be a problem. But right now, our priorities is getting complete Rust libstd support, since it's the primary toolchain and coding platform of the OS. Following next after that, as secondary languages, would be C and so on.

For your 2nd question, redirect that [here](https://github.com/redox-os/redox/issues/25).

**Comment by zonyitoo** [comment]
Redox could exports those syscall APIs to be able to called from C, then port the glibc/libc.

**Comment by jackpot51** [comment]
I have already ported most of libc, look in the libc directory

**Comment by jackpot51** [comment]
The lua app is a standard C program cross compiled for Redox, with no required code changes

**Comment by Ticki** [comment]
glibc/libc is the biggest task. When that's done, many programs are almost trivial to port.

**Comment by Ticki** [comment]
This falls under the task of making Redox Unix-compatible, so it can be closed.

**Comment by bubnenkoff** [comment]
So you do not like to get Redox Unix-compatible? So what way to get for example D compiler? It's much easier then C++, so in theory it would be much easier to get it on Redox.

**Comment by zonyitoo** [comment]
@bubnenkoff TMHO, @Ticki said this issue is part of the task of making Redox Unix-compatible.

**Comment by stratact** [comment]
Wait, what does supporting other compilers have to do with being Unix-compatible? It has to deal with wrapping C and C++ APIs to Redox syscalls in order to get other languages, like D, to build and work on Redox...?

**Comment by Ticki** [comment]
Porting libc is a part of the task of making it Unix-compatible.

**Comment by stratact** [comment]
But Redox already supports a libc called Newlib.

**Comment by stratact** [comment]
Alright, so as I found out, we are already Unix-compatible, along with support the Newlib libc implementation, so it is all taking care of.

**Comment by stratact** [comment]
@jackpot51 So all that is left is just supporting the other compilers?

**Comment by bubnenkoff** [comment]
And what need for example to get D on Redox?

**Comment by jackpot51** [comment]
You will need to cross compile it after building the cross compiler using libc/setup.sh

**Comment by bubnenkoff** [comment]
What problems I can get? Could anybody of more experienced members to get it work, if you of cource  have time for it.
And what about Rust? Is it's available for Redox?

**Comment by Ticki** [comment]
To port libc, you'd need to essentially replace all the parts which are platform dependent. And there're lots of 'em. So it takes some time.

On Rust, I assume you mean libstd. Libstd isn't ported yet, however libredox provides a pretty good replacement libstd. Neither is rustc ported, because it depends on LLVM and libstd.
