### ISSUE TITLE
Remove usage of floats in the kernel to speed up syscalls and context switches.

### ISSUE THREAD

**Issue by Ticki** [redox-os/redox#274]
There is a significant loss of performance when using floating points in the kernel space (due to interrupts). This is the same reason Linux forbids the use of floats in the kernel.

To complete this task, libcore needs to be patched, and the kernel needs to be floating-free.

See also:
- https://github.com/rust-lang/rfcs/issues/1364
- https://github.com/thepowersgang/rust-barebones-kernel/blob/master/libcore_nofp.patch

**Comment by tbelaire** [comment]
From my experience working on some stuff on the GBA, you don't require patching core, since `--gc-sections` is passed by default.  That means if you don't call any floating point operations, it won't link in the code that uses floating point.

But you might still have another problem, since Rust feels free to use the floating point registers when optimizing code that uses only ints.  SIMD things or something.  Anyways, you'll need to adjust your invocation of rustc or `target.json` to tell rust to not trample values in the floating point registers.

**Comment by jackpot51** [comment]
Float usage was disabled by patching libcore in the redox-os/rust repo
