### ISSUE TITLE
Add CONTRIBUTING.md to help people get started

### ISSUE THREAD

**Issue by skylerberg** [redox-os/redox#336]
Since I am figuring out how to best contribute (figure it out slowly due to very limited time at the moment), it seems like documenting what I learn would be a good idea. Post in this thread if you have ideas for what I should include in this document. Here is what I plan on writing about so far:

* Communication on slack
* GitHub issues
* Fork/merge workflow (brief overview)
* Continuous integration setup

Things I will include but need other people to clarify:
* Testing practices: Do we have testing practices beyond making sure it compiles? Are they run automatically? Are new commits expected to have tests for certain parts of the code base?
* Style guidelines: Are there any? Do we use any linting tools? Any guidelines for commit messages?
* Interactions with other projects: There are some other projects under the redox-os group on GitHub, how do they relate?
* Applications vs kernel: Not exactly sure what I want to know here, but I feel like there is something to write about this.
* Low-hanging fruit: What are easy targets for newbies?

The document needs to be informative and welcoming, so that is what I will aim for. I would love to hear feedback on what I should include. Thanks!

**Comment by stratact** [comment]
Regarding testing practices, for ZFS I made a test guideline based on the input from @tedsta for testing how ZFS works at runtime. This is currently pinned in the #zfs Slack channel for anyone to reference.

The ZFS test guidelines:
1. Create the zfs.img only once. If one has not been created, run `make filesystem/apps/zfs/zfs.img` before booting into Redox.
2. Run `open zfs.img` to open the created ZFS image.
3. Run `file /home/LICENSE.md` twice to ensure ARC isn't broken.

**Comment by stratact** [comment]
Also, it's better to run `make qemu` or `make virtualbox` rather than `make all`, because it is important to see how the OS boots and works after it compiles. Just because the code compiles doesn't always mean it will run as you expect. I had that happen to me when messing with kernel and it screwed up how Orbital works. So this, in my opinion, is the most fundamental testing practice for Redox.

**Comment by stratact** [comment]
and another good testing practice for the kernel. When trying to access a slice, always always **ALWAYS** use the `common::GetSlice` trait and use the `.get_slice()` method to get a slice without causing the kernel to panic. The problem with slicing in regular Rust, e.g. `foo[a..b]`, is that if someone tries to access with a range that is out of bounds of an array/string/slice, it will cause a panic at runtime, as a safety measure. Same thing when accessing an element. Always use `foo.get(n)` instead of `foo[n]` and try to cover for the possibility of `Option::None`. Doing the regular way may work fine for applications, but never in the kernel. No possible panics should ever exist in kernel space.

**Comment by skylerberg** [comment]
Based on @stratact and I's discussion on slack, here are some ideas for how people not fluent in Rust can get started with the project:
* Documentation
* Using redox (and filing issues for bugs and needed features)
* Web development (Redox website)
* Unit tests

**Comment by stratact** [comment]
and also running the tests from `filesystem/apps/test/main.rs`

**Comment by polymetric1** [comment]
is anyone already doing this? I could start working on it if no one else is

**Comment by skylerberg** [comment]
Go for it! I was planning to do it eventually, but I am not sure when I am going to have any time.

**Comment by polymetric1** [comment]
alright, I'll start as soon as I get to my PC

**Comment by skylerberg** [comment]
Thanks, @polymetric1! Since we have a merged CONTRIBUTING.md, I am closing this.
