### ISSUE TITLE
[architecture ] Everything is a channel

### ISSUE THREAD

**Issue by vitiral** [redox-os/redox#358]
I came across your project recently and have begun to think of the advancements that could be made to a modern kernel. I think much of the work of a modern kernel should be consolidating good ideas from other areas of computing. 

On such idea is revising the "everything is a file" idea to "everything is a channel", specifically a typed ring buffer channel. 

What are the benefits of channels at the kernel level? 
- can be used to handle concurrency and locking, allowing for true asyncio - similar to how golang works with their goroutines + channels 
- allow transmission of more complex datatypes than a simple bytestream 
- can be more easily consumed by multiple threads 

Combining the "everything is a url"  with "everything is a channel" gives you even more power, as the url can specify the type. Perhaps the ONLY way to get a non-file-like channel should be through the url format (explicit is better than implicit) 

Channels allow a more unified and extensible interface for both kernel -> kernel and kernel -> userspace communication, and it does so with better asyncio support (programs could elect to block until at least one of their channels are available, etc) 

Anyway, I'm currently learning rust, so can't contribute much ATM, but wanted to leave this idea.

**Comment by Ticki** [comment]
Could you elaborate on what you excatly mean by "channel"? How is it different from url, and what controls and defines it?

**Comment by Ticki** [comment]
Also, in what way is it typed?

**Comment by polymetric1** [comment]
I think he might mean something like an I/O stream.

**Comment by polymetric1** [comment]
Is this what you're talking about? https://en.m.wikipedia.org/wiki/Circular_buffer

**Comment by polymetric1** [comment]
If I understand what you mean, and the URL stuff in Redox, that's sort of what we're already doing with URLs, you can send bytes to them like a data stream.

**Comment by tedsta** [comment]
I think he means channels as they are in Rust, Go, and friends. https://doc.rust-lang.org/nightly/std/sync/mpsc/fn.channel.html

I think the main problem with this is integration with all of the languages. Regular byte streams are extremely portable and typed channels can be implemented on top of them.

**Comment by vitiral** [comment]
@tedsta Yes, I mean channels as they exist in modern languages, like you said.

Simplicity is a very valid goal, but so is safetey, validity and performance (rust itself strikes me as a very good balance between these goals).

Typed channels would not be difficult to implement -- instead of a byte stream you would have a cirtular buffer of basic structs (something every language can implement). The structure of the type would be expressed in a user readable manner (i.e. json) and be retrieved from something like the `type::/value` system url. Let's look at a tcp packet from a socket.

In the unix world, if I want to read from a socket I use a socket.read(size) method. This is besides the fact that the actual data is gotten in frames and so could be delivered in frames -- no memory should have to (necessarily) be allocated by the user program to receive a packet and deal with it. I (hardly) ever care about partial data in a packet -- why should I be reading it in 1024 byte chunks when this memory is already allocated by the OS?

A better solution would be to deliver the data in a packet struct, like so:

```
struct packet {
uint16t source_port;
uint16t dest_port;
etc...
uint16t window_size;
uint16t checksum;
uint8t data[];
}
```

`type::/socket` would return a simple json (or other) format for this data:
```
{
'buffer': 'ring_pointer',   # the buffer is a ring buffer with pointers to the resultant data
'output': {  # type of output
    'name': 'packet',
    'struct': [
        {'name': 'source_port'',
         'type': 'uint16_t'},
        etc
    ]
}
}
```

There are probably better examples than sockets/packets, but the general idea should be apparent.

The benefits of this are obvious - with an efficient means to communicate (eliminating the need for userspace programs to even allocate memory to create a struct!) concurrency and communication among programs (and between computers) could be muh faster, and would directly map with modern languages.

**Comment by Ticki** [comment]
So what you mean is a non-blocking, real time, socket between processes?

**Comment by tedsta** [comment]
While datagrams will be a common pattern, what about files? For instance, `file:/home/teddy/notes.txt`. Right now, under the hood libredox (spoofed as libstd) uses a scheme to open files for reading and writing.

Call stack:
- https://github.com/redox-os/redox/tree/02d3b4669caedbadea2fa7fd280e9230ebad3763/libredox/src/fs.rs#L21
- https://github.com/redox-os/redox/tree/02d3b4669caedbadea2fa7fd280e9230ebad3763/kernel/syscall/handle.rs#L530
- https://github.com/redox-os/redox/tree/02d3b4669caedbadea2fa7fd280e9230ebad3763/kernel/env/mod.rs#L71-L97

The struct is nice to work with. But the CPU efficiency of the binary struct is lost because you have to parse the human readable json to construct it.

If writes are atomic, channels can be done with serialization. With [serde](https://github.com/serde-rs/serde) it'd look something like:

Sending:
```Rust
file.write(serde_bin::to_bytes(msg));
```

Receiving:
```Rust
file.write(serde_bin::to_bytes(msg));
```

A scheme could support both binary and json encodings. Mark binary messages with an initial '\255' or something. If the first byte doesn't signify a binary message, read json:
```Rust
let msg: Packet = serde_json::from_string(file.read());
```

Serde is only for Rust, though. But, we could use something like [msgpack](http://msgpack.org/), which has a serde backend [msgpack-rust](https://github.com/3Hren/msgpack-rust), and benefit from the existing msgpack implementations for the various languages. Or whatever serialization system, we could make our own. There could be a helper crate to standardize/abstract any boilerplate (with bindings for other languages).

**Comment by Ticki** [comment]
@jackpot51, what do you think about this idea?

**Comment by vitiral** [comment]
> The struct is nice to work with. But the CPU efficiency of the binary struct is lost because you have to parse the human readable json to construct it.

I think maybe I shouldn't have included the json type - - in reality I think that the types of the channels should be REALLY frozen, and if they ever change can only change between major versions (i.e breaking changes). 

So at the worst case you would only parse the json when you started your program. Also, I think you are right that the struct encoding should be in binary format, and have a url to get it in json (i.e. type-json::/value to get it in human readable format). Really the type is there only so programs can validate that their channel type is accurate. 

The other thing, which I think you are getting at, is this would allow you to specify packets to send between processes. So you could send a specific length of binary data to another process, which it could then use msgpack or json to decode. All you would need is a struct of u8 data with a length at the start.

**Comment by vitiral** [comment]
I did have a thought, which is if you are communicating userspace <-> userspace. For these types of things, you would have to specify the data type when the channel was opened,not at program in it, for obvious reasons. 

I was mostly thinking of kernel communication with userspace and with the kernel, in which you should only check the type at the start of the program (if you are wondering how you would kexec between major versions... I don't know right now. You might have to restart programs who's channels have changed)

**Comment by tedsta** [comment]
> I think maybe I shouldn't have included the json type

I read too quickly and misunderstood your proposal. I thought you meant the messages were delivered as json, not binary, then deserialized. I see now that the json describes the (binary) message type and is not a message itself. My bad.

I do like the idea of strongly typed communication in schemes, but I'm not convinced that everything *can* be a channel (for instance, the `file:` scheme). I think your idea could be implemented as a helper library for schemes whose `Resource`s (files) work like channels.

Take everything I say with a grain of salt. IMO, Redox is still a fetus. @jackpot51 is the authority on all of this, and he has spent most of his time coding rather than documenting so far (understandably). So, as far as I know, there isn't a detailed write-up of the "everything is a scheme" pattern and what it means. So, my understanding of all of this may be off.

**Comment by vitiral** [comment]
A file would just be a ring buffer with the type "u8". This should be about as performant as is possible. 

Note: things like a "readline" file type would be easy to implement, where the root would handle splitting lines for better efficiency. But that is off topic 

I think maybe I need to elaborate on how the ring buffers would work. 

There would be two kinds: waiting and non-waiting. Both of them would store:

- the root index the buffer is at. This would increment until bufsize % uint_max, where it would wrap. If the buffer size is 10, and the index is 21 that means the first index has been overwritten twice and every other index overwritten once. 
- the index that user programs are at, set by the program itself. Indicates up to which index was read

Waiting buffers would be for something like reading a file or a top socket. The root index would never go above the user index + bufsize as this would cause data corruption , it would wait for the program to indicate it has read from the buffer. 

Non waiting buffers would be for something like a com port or a udp socket, where it is the applications job to ensure it reads data fast enough. It would be the applications job to die or otherwise handle the error if the root wrote over unread data.

**Comment by vitiral** [comment]
OK, thanks for hearing me out everyone!

**Comment by Ticki** [comment]
@jackpot51 Why is this closed without any reason behind?

**Comment by jackpot51** [comment]
Oops, hit the wrong button

**Comment by Ticki** [comment]
No problem @jackpot51 :)

**Comment by jackpot51** [comment]
I see no reason why specific schemes couldn't operate this way already, to wrap around when they hit the end and to deliver structs out of their byte streams

**Comment by jackpot51** [comment]
would someone be willing to write an example scheme for this?

**Comment by Ticki** [comment]
I guess the point is that schemes are sync and not async as channels proposed here.

**Comment by Ticki** [comment]
A live byte stream (not neccesarily typed) would be neat, but it's not possible with schemes because of their "on-demand" nature.

**Comment by jackpot51** [comment]
True, we will get to async i/o eventually. If we had the async read, write, seek, I think this would be completely implementable

**Comment by jackpot51** [comment]
I wouldn't default to this, and see no reason to call it channels. This is what unix domain sockets and fifos do

**Comment by Ticki** [comment]
No, neither I would default to it, but it seems to be better to have this feature as a part of the OS itself, instead of having different programs utilizing different methods for this. I think 'Channels' are a great idea for certain task but not all.

**Comment by Ticki** [comment]
A obvious usecase is TCP or other kinds of sockets and external IO communication.

**Comment by jackpot51** [comment]
They are called sockets... Why call them channels?

**Comment by Ticki** [comment]
Hence the `'`, because of the title of this post.

**Comment by polymetric1** [comment]
Kinda off topic: is a scheme a Rust thing, or a Redox thing? Either way where can I read about them? because I don't entirely understand what they are.

**Comment by Ticki** [comment]
A Redox thing.

**Comment by Ticki** [comment]
Short explaination: Schemes are files on steriods.

**Comment by Ticki** [comment]
Instead of "everything is a file" we got "everything is a scheme" (or "everything is a url").

**Comment by polymetric1** [comment]
Oh okay. Thanks

**Comment by Ticki** [comment]
So essentially segregated filesystems from which you can read, write, seek etc.

**Comment by stratact** [comment]
> Short explaination: Schemes are files on steriods.

Wait, Schemes are the type of handler for URLs. URLs are the files on steroids?

**Comment by Ticki** [comment]
URLs -> Resources -> Schemes.

**Comment by tedsta** [comment]
Aren't sockets also just a stream of bytes, not typed? `Channel<T>` is a stream of `T`.

Isn't TCP supposed to simulate a stream of bytes? UDP would follow the channel pattern though I think.

My understanding of schemes is this: URLs have a corresponding scheme which opens them, denoted by the `<scheme>:` portion of the URL, which returns a file which can be read from and written to. That's how you open files in redox. Different schemes work in different ways. The `orbital:` scheme processes data you write to files opened from it as commands for the window manager. The `file:` scheme simply opens files from the filesystem for you. The `tcp:` scheme let's you open TCP sockets. And so on.

And so, the nice thing about this proposal is we get consistent, strongly typed communication between schemes and processes with files open from them. I guess at this point what we are debating is at what layer in Redox this is suitable to implement in, and whether or not we should force all schemes give out channels. The nice thing about making all schemes give out channels is everything is consistent.

My current position is that this could be implemented on top of what we already have, rather than changing `Resource` to be a channel and forcing all schemes to follow the channel pattern. To make sure that everyone and their mother doesn't have their own scheme channel implementation, we could make a "blessed" implementation that everyone is supposed to use. 

What do you guys think about this:

Schemes stay as they are now. We create a library which allows schemes and URL openers to communicate conveniently using a channel-like API, among other things. It's just an API for working with schemes. Note that channels are one-way, so the library would have to support both `scheme -> url opener` and `scheme <- url opener`. The scheme @vitiral proposed that returns json metadata describing the type of a scheme's channel could return the type of the *scheme* itself.

- Is it a channel? If so, what type and what direction?
- Plain old file?
- etc.

This opens up the door for all kinds of patterns/data-structures, still under a unified interface. I think that's a pretty decent compromise. What do you think, @vitiral?

**Comment by vitiral** [comment]
I guess the main thing I don't understand is what the difference is between a `scheme` and a ringbuffer of bytes. I would think they would be *very* similar, if not identical. Maybe this is something I need to read the source to understand, if so tell me to shutup and I'll get back to learning rust until I can contribute something :)

All a `channel` is is a ringbuffer of <insert type of data here> with a few integers denoting what has been read and what has been written. As far as I know, ringbuffers are damn near the fastest possible method of buffered communication, so would be a fine method to implement your `schemes`.

Let's do this.
- disregard the terminalogy `channel`. The proposal is this: let's make a `scheme` a typed ringbuffer.
- advantages of a typed ringbuffer
    - fast and efficient
    - simple to construct and explain
    - better asyncio at the kernel level (kernel can use the read_index and write_index to block when no data is available and schedule only when data is available -- as well as pause i/o if the user-program isn't keeping up)
    - can easily mimick traditional file i/o, so can be compatible with many unix tools (as far as I know).
- the implementation as a typed ringbuffer was taken from modern `channels`, which is much how the proposed `scheme` is intended to function in an application (be type-safe, help with scheduling/blocking, etc.)

Some thoughts on your post:
- I don't know exactly what the UNIX spec is for sockets, but their underlying implementation sends data in packets which have a set size. As far as I know, user applications never receieve bytes until at least one full packet is in, so I've never understood why the user application should receive one byte at a time (and have to specify a length) when the entire packet with length information is already available in memory.
- In general, I would like to get away from byte-streams except for where they make sense (COM ports, file i/o, etc.). It would be great to be able to communicate CPU temperature with a channel of `f64`, communicate with USB using the actual packets in the spec, etc (this is why it can't be called a `socket` -- because the new `scheme` would need more types than a packet). Of course, sometimes all you *want* is a bytestream, in which case the conversion to a bytestream should also be available (through something like `tcp-bytes::/`.
- I would think that implementing a typed ringbuffer on top of a byte stream would only worsen complexity and be more error prone. Isn't this what user programs are already doing?

**Comment by tedsta** [comment]
A scheme is an entity that sticks around and responds to URL opens. When you open a URL, you get a `Resource` back, which is a file - it's just a buffer of bytes with a seek position.

Can both the scheme and the URL opener read from and write to the ring buffer?

**Comment by stratact** [comment]
Like I was saying earlier, the focus should be on the URL, not the Scheme. The Schemes are just the types of ways to work on any paths or configurations. Like how I view it here:
```
[----------------URL----------------]
[ [Scheme:] [Path or Configuration] ]
```

**Comment by Ticki** [comment]
@stratact The communication happens through the scheme not the URL. The URL is just a descriptor.

**Comment by vitiral** [comment]
@tedsta yes, you would need two ring buffers for two way communication.

I guess one difference is the "seek" ability. You would not be able to seek past where the write index is, although I'm not sure how you would implement seek for normal buffers without loading everything into memory (or clearing the buffer when seek is called). You could certainly do the second with a ring buffer.

**Comment by tedsta** [comment]
@Ticki: I wouldn't say the communication happens "through" the scheme. Here's how I would describe it: The scheme is an end point, the process who opened the URL being the other end point. The buffer through which they communicate is created by the scheme and is identified by the URL.

Alright, I think I'm convinced that this could be implemented in the kernel. In theory, it's easy to implement. Unfortunately, you can create a trait object with a trait that has generic methods.

Here's my thought process:
- The `Resource` trait works with a type parameter, `T`, instead of `u8`, so `Resource<T>`.
- `KScheme::open` becomes `fn open<T>(&mut self, url: &Url, flags: usize) -> Option<Box<Resource<T>>>`. This is where the problem is. All of the schemes are boxed and stored in an array. Can't create the trait object if KScheme::open becomes generic.
- Semantics of `Resource<T>` methods change slightly:
    - An async read will return the data if available, otherwise an error.
    - An async write will write if there is room in the ring buffer, grow the ring buffer and write if the caller-specified flags allow it and the reallocation succeeds, otherwise return an error.
    - A sync read will return the data when it is available, blocking until it is available.
    - A sync write will write the data when there is room on the ring buffer, blocking until the space is available.

I'm sure we can get around this with some unsafe pointer hackery, but I have to mull on how to package it up nicely and safely.

**Comment by tedsta** [comment]
Actually, schemes would have to be able to work with multiple channel types for this to be flexible enough. So, `KScheme` would stay a non-generic, but `KScheme::open` would have to become generic. Now we can make the array, but can't actually construct the trait objects because trait object traits can't have generic methods.

Perhaps there's a wrapper scheme, `KSchemeWrap` that returns the `Box<Resource<T>>` data as a bunch of bytes. On the userspace side, the syscall wrappers transmute the data back into the resource type. We'd have to do sanity checking regarding the type stuff. Or, we could just trust the user and let them crash if they get it wrong.

**Comment by jackpot51** [comment]
This is no longer relevant with the way that schemes have developed in the kernel.

Scheme communication can be nonblocking, socket-like (orbital:) or filesystem-like (file:). Therefore, I think the intent of this issue has in some ways been met. If not, I would prefer that more specific issues concerning the current architecture
