### ISSUE TITLE
Window management

### ISSUE THREAD

**Issue by stryan** [redox-os/redox#37]
I'd like to start working on a window manager so that we don't have stuff like file-manager spawning at random locations across the screen. Any thoughts on how this should go? Personally, I'd like to follow plan 9/wmii and and eventually expose windows as files/URLS.

**Comment by jackpot51** [comment]
I would love to get this fixed.

window:// or gui:// could be exposed. I want to get rid of those WINDOW_CREATE and WINDOW_DESTROY syscalls, they are so unnecessary and disallow a userspace windowing system!

The place to start would be to copy one of the simpler schemes, random:// is a good example. It needs to be pushed in kernel.rs for now (until schemes are modular). If you have *any* questions about this, I will try to fill you in, because it is a very good cleanup to do.

The irc is at irc://irc.mozilla.org/redox if you want to chat there.

I have added you to the window management group

**Comment by stryan** [comment]
Okay, my current roadmap for this is 
1) Expose window:// so that windows can work with each other.
2) Reimplement WINDOW_CREATE and WINDOW_DESTROY outside of syscalls. Why was that done this way anyway? Can programs not access the current session otherwise?
3) Rewrite window.rs to create and destroy windows properly.

I'll get working on it this weekend.

**Comment by jackpot51** [comment]
That's correct.

1) You can look at other schemes for examples, but a open should create a window, drop should destroy (i. e. window:///640/480)
2) Because it started in kernel land, and I just hacked windowing into userland with a couple of lines of code. Pretty efficient, but very not correct
3) That's right, it would now need to interface with window:// to redraw, create, and destroy

Thanks! Let me know if you need help

**Comment by jackpot51** [comment]
Since we took care of this, I am closing the issue
