### ISSUE TITLE
Start RFC-like process for OS features and documentation

### ISSUE THREAD

**Issue by hauleth** [redox-os/redox#405]
We should take the example from Plan 9 and FreeBSD where the most important feature is stability and great documentation. Currently development process is like to the Linux one which is quite chaotic. What do you think?

Of course this will slow down development a little bit, but this also will help with providing much more stable and reliable product, which will IMHO help us with gaining users.

**Comment by Ticki** [comment]
I think it's too early for that, actually.

**Comment by hauleth** [comment]
I think not. There should be at least paper that would describe main goals and design principles of Redox. This would help us with establishing direction which development will take. It is very important to have idealised goal that we will try to reach.

**Comment by Ticki** [comment]
I'm just thinking that it's too early to introduce this formal beast is too early, since our discussions are already active and well-functioning on Github and Mattermost.

**Comment by joeblew99** [comment]
I am a user, not developer, but looking for things that help building projects. Anything that gives high level use cases of how how redux can help a user is worthwhile.

For example:
If running a cloud, will it help stability or runtime speed ?

Will if provide functionality that a standard Linux OS can't provide ?

Will it run on arm or embedded with a CPU ( as opposed to an MCU )

**Comment by polymetric1** [comment]
@joeblew99 To answer your (vague) question:

0. I assume by "running a cloud", you mean server, when people say "the cloud" they usually mean servers or some other part of the network that doesn't matter. In the far future when Redox is fit for production use, it may be faster and more stable because Rust code is easier to manage, the language is much more modern than C, and more efficient. So likely.
0. Probably not, I mean what functionality does Linux not provide that you would want?
0. Yes, of course eventually. We're currently still having problems with _x86_, let alone x86_64 or ARM.

So, yes to most of these (except #2), but not in the near future. We're still in very early development.
Also, this isn't the right place to ask these questions. I'd probably suggest the #redox channel on the Mozilla IRC.

**Comment by joeblew99** [comment]
Ok cheers for answers.  That sort of high level info does help

**Comment by Ticki** [comment]
Well, you might also want to check out @Roxxik/redox-docs!

**Comment by jackpot51** [comment]
I don't see this as being necessary. Right now we have a long list of things that must be done, going through RFCs is just another hassle to maintain

**Comment by stratact** [comment]
While we're not in the state of doing this and probably not for a long time, wouldn't it make more sense to assign this issue with labels, like `low-priority` and/or `long-term`, because it is important in the long run to follow a more integrated approach like with FreeBSD, where we care about everything in the OS and how they fit together?
