### ISSUE TITLE
Improve context switch performance

### ISSUE THREAD

**Issue by jackpot51** [redox-os/redox#486]
Right now, Redox switches are **slow.** As we are moving into microkernel space, the requirement of having several context switches means that we really need to get the time down, or the system will be unusable. Currently, the orbital branch gets behind on moving mouse events because of this issue.

The major issue is the virtual memory swap. If the context memory was stored in a page table, it could be written to cr3 directly, removing a large amount of work. Designing such a system will be difficult, and require thorough testing

**Comment by Roxxik** [comment]
This needs a major refactoring of the interrupt tables and the kernel routine in kernel/main.rs
Maybe put a custom interrupt handler for 0x20? So we don't have to refactor all the interrupt code.

**Comment by genodeftest** [comment]
Just a minor thing, but you probably could use SYSCALL/SYSRET (AMD) and SYSENTER/SYSEXIT (Intel) instructions instead of `int 0x80`. [Docs](http://wiki.osdev.org/SYSENTER#Compatibility_across_Intel_and_AMD)

**Comment by ERnsTL** [comment]
I recently read about [an interesting solution](http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.105.601) called *KLOS: A High Performance Kernel-Less Operating System*, which surpassed even the performance of SYSCALL/SYSENTER instructions by completely avoiding CPU ring transitions.

They validated their concept using a small kernel and userland implementation. Highly interesting. Might be worth trying out before the "ring transition for security" pattern becomes cemented in Redox.

**Comment by Roxxik** [comment]
using something else then int 0x80, either syscall or sysenter or something totally different(read that paper too) would increase context switch performance alittle, i agree, but reworking the current memory handling code to not rewrite all page mappings on each context switch, will improve performance alot.

**Comment by Roxxik** [comment]
ok now i read the KLOS paper and i have to say, that their security foundations is rather stochastic and i'm not sure how this fits into the goals of redox. Besides this operating system relies so heavily on x86 for their basis, that it's hard to imagine a way to port it to another architecture

**Comment by Ticki** [comment]
> using something else then int 0x80, either syscall or sysenter or something totally different, would increase context switch performance alittle

I don't think the difference would be noticable.

> reworking the current memory handling code to not rewrite all page mappings on each context switch, will improve performance alot.

Yes, this is the biggest source (currently) of slowness. This is something that should improved a lot.

A more radical idea would be the one presented in "A New Protection Model for Component-Based Operating Systems" by Greg Law and Julie McCann, where they present a model where drivers run in ring 0, while still being unprivileged, through a method they call 'code-scanning', which is a form of primtive static analysis taking place, when the executable is mapped.

But I think that the model presented by Vasudevan et al. would be more fitting for our current design. Even though, it would be prefferable to use a more well-developed technique.

**Comment by Ticki** [comment]
> security foundations is rather stochastic and i'm not sure how this fits into the goals of redox.

It is pretty much non-existing. Breaking it would be trivial.

**Comment by genodeftest** [comment]
> ok now i read the KLOS paper and i have to say, that their security foundations is rather stochastic and i'm not sure how this fits into the goals of redox. Besides this operating system relies so heavily on x86 for their basis, that it's hard to imagine a way to port it to another architecture

Not to say: They just hope it is safe. A 1.83*10−4 chance in breaking the system is quite much. And the way they "mitigate" this breach is not stopping anybody from just trying again. A 1.83*10−4 chance with hundreds of tries per second is a sure hit when running for more than an hour. So this concept is utterly broken.

> A more radical idea would be the one presented in "A New Protection Model for Component-Based Operating Systems" by Greg Law and Julie McCann, where they present a model where drivers run in ring 0, while still being unprivileged, through a method they call 'code-scanning', which is a form of primitive static analysis taking place, when the executable is mapped.

That breaks as soon as the driver jumps to data on stack or heap or starts executing data it got from the device. And it is a blacklisting-approach, meaning that every single mistake will be fatal. I'd prefer white listing approaches like paging and running code unprivileged.

**Comment by Ticki** [comment]
> That breaks as soon as the driver jumps to data on stack or heap or starts executing data it got from the device.

Which is where you'd insert runtime checks.

**Comment by genodeftest** [comment]
The FlexSC approach seems way better, especially since it is in fact an asynchronous inter process communication concept. It basically sends syscalls as messages on a different thread, working around having thousands of cycles wasted for MMU and mode switch. It is especially useful for redox since data will be passed through several processes (kernel → filesystem → disk interface driver → disk driver). Since Rust is memory safe anyway (and thus easy to get thread safe) implementation shouldn't be too hard.
Functionality implemented in the kernel (with filesystem, etc. removed from it) would still be using synchronous syscalls, but communication with the other processes would be message-based IPC.

Disadvantages:
* different from posix/unix syscalls
* more threading: performance gain for high-load application requires the use of Green Threads

**Comment by Ticki** [comment]
@genodeftest I dislike that approach, it seems like a very heavy way to go, furthermore having Unix compatible syscalls would effectively mean that there would be double functionality, which is not prefferable.

**Comment by andrebrait** [comment]
As a computer engineering student without much free time but who likes OSes (and low level stuff in general) quite a lot, I found this discussion amazing. I love FLOSS and although I have my problems with the MIT license thing (not starting a discussion, just stating a fact about me) I found Redox so interesting I couldn't stop reading the documentation and learning Rust since when I got to know it existed. A microkernel (the one thing I hate about Linux is its monolithic design) made (mostly) in a new, memory and thread safe by design programming language which still reminds me of C and has a (surprisingly) elegant syntax... It's like a dream.

I always thought 'how do people design those big OSes?' and now I get to see it from the start. I'm not even that young (27) but I felt like a chid who likes dinosaurs and goes to the natural history museumbfor the first time. Of course I could read stuff about Linux, but I have no time and the gap between 'hey, check this system I made based on minix" and the behemoth it is today is quite large. Getting to see the start of such a beautiful project is just amazing.

I seriously look forward to contributing as soon as I can. I need sometimes to escape this sad, web-developer filled world I live in (working as a Java EE developer, but I don't quite like web stuff)

**Comment by jackpot51** [comment]
This has been taken care of in the new kernel

**Comment by sinkarharshad** [comment]
@jackpot51  Is there any ```top``` equivalent command or an alternative way where we can measure following listed things: (e.g w.r.t. thread)
- Consumed Time
- Memory
- Number of Context switches (really interested to know as redox is using "bulk-syscalls")
- %cpu used (Just in case if we compare with Linux or any other OS'es)

Appreciate your time and thank you in advance :)
