### ISSUE TITLE
Modern Terminal

### ISSUE THREAD

**Issue by coder543** [redox-os/redox#569]
Has the Redox team considered making a modern terminal experience, rather than re-implementing yet another ANSI terminal with the traditional text-based UNIX commands? I believe there is an opportunity to really revolutionize how the terminal works, and make a superior experience, rather than just an equivalent one.

Having an ANSI terminal with standard UNIX commands would be useful for backwards compatibility and portability, of course, but I would like to see (and would love to implement, if I had time right now) a modern experience that might be centered around passing objects (like Powershell) rather than plaintext, while having useful features derived from [Final Term](http://worldwidemann.com/final-term-a-modern-terminal-emulator/).

I might find time to start working on this soon, but things are a bit crazy here for the next couple of months. While Redox is still young, changes like this can still be made, but once it gets more mature, it would obviously be harder for something like this to get traction, which is why I wanted to go ahead and throw this out there, see if there was any feedback from the community.

**Comment by Ticki** [comment]
I have proposed this before, and I would certainly be interested in this. ANSI is old and clumsy (example: entering raw mode requires ioctl call, numbers are base 10 encoded, it is slow, no way to draw arbitrary pixels, etc.).

Furthermore, compatibility should not be a concern, since you can simply provide escape code translators. Terminal libraries can also easily be modified to a new set of escapes.

> Having an ANSI terminal with standard UNIX commands would be useful for backwards compatibility and portability

You are confusing terminals with shells. A new set of escape codes will not change shells at all.

**Comment by ERnsTL** [comment]
Adding my two cents, I once read [this excellent primer](http://www.linusakesson.net/programming/tty/) by Linus Akesson, explaining the rationale behind the various historical reasons why *my Linux terminal session has a baud rate*, how the back and forth communication works etc. This a PC, not me talking to a server from a terminal device over a serial line. All terminals are virtual today, yet all this emulation takes place, so it looks like a pile of historically-grown cruft to me. I doubt that a terminfo database is really neccessary in 2016.

HelenOS [makes this statement](http://www.helenos.org/wiki/DiffFromUnix): 

> **No serial terminals**
>
> In the world of UNIX-like operating systems command-line applications can make use of a pseudo-graphical UI via [n]curses or a similar library. This provides commands like move cursor, set color, etc. Conversely keyboard input (including some control keys like arrows, Page Up, etc) can be retrieved by the application. However only a dumb serial line / character device is assumed to connect the application to the console.
>
>Therefore all the pseudo-graphical commands are marshaled into a character stream (escape sequences) by the curses library and unmarshaled by the console. Conversely the keyboard input is marshaled by the console and unmarshaled by the curses library. This is the common cause of many problems.
>
> In HelenOS the application talks directly to the console via an IPC interface. 

Redox OS could also follow this idea.

IMHO, a terminal should have these desireable properties:

* inline graphics support to allow stuff like w3m and [termpdf](https://github.com/dsanson/termpdf)
* mouse-clicking support
* windowing like in ncurses or VT100
* API-based, not serial-based with all kinds of escape codes

---

To comment on UNIX pipes: They are so versatile, because they transport the universal format: strings. For an explanation of their power, see the string-based Property Pattern TODO and why text-based Internet protocols were so popular. Drawback: Strings are also *untyped*.

If you take typed pipes to the extreme, you end up with [GStreamer](https://gstreamer.freedesktop.org/) or [dataflow programming](https://en.wikipedia.org/wiki/Dataflow_programming). Some systems like [Pd / Pure Data](http://puredata.info/) have made this work, but not sure if such a system is desirable as a goal for passing simple data structures between processes.

**Comment by Ticki** [comment]
I'd avoid typed pipelines, for the obvious drawbacks they carry. But being without a modern terminal, would be a missed chance for Redox. I do not think that design nor implementation would be hard.

> API-based, not serial-based with all kinds of escape codes

I'd actually like it to be serial-based, since doing so is much simpler, and more language agnostic.

**Comment by ERnsTL** [comment]
The [Final Term](http://worldwidemann.com/final-term-a-modern-terminal-emulator/) mentioned by @coder543 looks uselful, thumbs up.

The otherwise disputable TempleOS also features a text-based GUI / shell with [some note-worthy properties](http://www.codersnotes.com/notes/a-constructive-look-at-templeos/).

**Comment by Ticki** [comment]
TempleOS do actually have pleanty of good ideas, despite often being railed upon. So :+1:.

**Comment by coder543** [comment]
> I'd avoid typed pipelines, for the obvious drawbacks they carry.

There are some drawbacks, but the advantages can be pretty large. PowerShell is [all about typed pipelines](https://technet.microsoft.com/en-us/library/dd347728.aspx), and it actually makes PowerShell incredibly powerful. I'm not sure which drawbacks you're looking to avoid though. I think the performance would almost be better using a protocol buffer stream instead of raw strings for many applications, since you're no longer having to parse strings into objects, then turn it back into a string for the next stage of the pipeline over and over. You only stringify it once at the very end when it needs to be displayed to the user.

If a set of Standard Types were developed for the pipeline as Protocol Buffer specifications, these could be shared between applications and used creatively. The beginning of the pipeline stream could specify which Standard Type is being used. It has the potential to make a very interesting IPC scheme, and if there were a Standard Types crate/library then all of that could be abstracted away from individual applications. If all they want is a string, they could request ST to stringify, but I think most applications would be perfectly content to work at a type-safe, object level. Did I mention type-safety? That could be nice as well.

I'm not sure what all should be included in a set of Standard Types for pipelining information between processes, but you could always have a fallback buffer for basically raw strings, and the performance impact would be minimal. I dunno. Just my thoughts.



I've been reading ERnsTL's link and I thought this blockquote was worth calling out:

> How much support code does it take to open a window and draw graphics into it on your operating system? In TempleOS, there is a one-to-one correspondence between tasks and windows, so a single call to DCAlias is enough to return the device context for your window. You can just do this as soon as your main function is called and draw into it. Making a window is surely the most important thing for a windowed operating system - why does it have to be hard? GDI, X11, DirectX and OpenGL could all learn something here.

Not 100% related to having a modern terminal experience, but certainly something I agree with.

**Comment by JasperWallace** [comment]
(dumping my notes of similar things)

Modernish graphical terminal: http://acko.net/blog/on-termkit/

An older, but similar thing using XML based on Netscape: http://www.xml.com/lpt/a/425

The hotwire shell, "an object-oriented hypershell": https://code.google.com/archive/p/hotwire-shell/

Has a nice list of links: https://code.google.com/archive/p/hotwire-shell/wikis/RelatedProjectsAndIdeas.wiki

Interesting Advogato thread:  http://www.advogato.org/article/242.html

GUSH: http://wiki.tcl.tk/23446
http://suso.suso.org/xulu/Command_Line_Magic
http://almaer.com/blog/commandline2dot0

Problems with existing shell stuff:

Imagine that your companies file server is running low on disk space and you want to see who the top 10 users are. You can "cd /home; sudo du -s * | sort -rn | head -10" but it would be nice to have the sizes in more human readable formats, so you add -h to du, and now your output is broken beacause 576K sorts after 451M...

Sort does have a -h option to interpret humanised numbers, but you have to remember to use it.

It would be much nicer if tools internally kept numbers as numbers and only formatted them when showing them to a person.

Adding humanised numbers to existing tools can break scripts - see this thread about humanising the output of dd: https://mail-index.netbsd.org/tech-userlevel/2010/12/03/msg004179.html

Another problem is the "find . -print | xargs something" pattern - it gets broken by paths with spaces in them.

**Comment by jackpot51** [comment]
While possible to implement a terminal using an internal object syntax, I do not see such a thing becoming the default in Redox. Our current terminal, shell, and utils are all ANSI-based, and work well

**Comment by Eisfreak7** [comment]
Has this been discussed internally? @ticki among others seem to be in favor of it, and despite yours there has been basically no negative feedback. I understand that you are the "BDFL" here and I'm in no position to complain, I just think that the community should be more involved in big decisions like this.
(A similar situation is #172)

**Comment by ticki** [comment]
>  I understand that you are the "BDFL" here and I'm in no position to complain, I just think that the community should be more involved in big decisions like this.
(A similar situation is #172)

eh, that's a misunderstand. BDFL = the person taking the final hard decision, not dictator who will kill you if you complain.

> Has this been discussed internally?

Yes, and the conclusion was that it is not plausible given the etablished design and support of ANSI. We have multiple extensions to ANSI in mind, though.

**Comment by leeoniya** [comment]
@ticki @Eisfreak7

i'd like to voice a similar concern for summarily closing https://github.com/redox-os/redox/issues/634 for what amounted to "too much feedback".

**Comment by ticki** [comment]
@leeoniya, fair point, but it is off-topic for this thread. Leave a comment in that issue instead.

**Comment by jackpot51** [comment]
To anyone who would like to discuss this, I propose creating an RFC here: https://github.com/redox-os/rfcs

We will be trying to move these kinds of issues, which are more theoretical and require a lot of discussion, to RFCs

**Comment by Eisfreak7** [comment]
Thats great, thank you.
Would it be of any use to open a rfc there just for a discussion though? I lack the knowledge for any detailed plans and (at least currently) the time for an implementation, and thats what a rfc would be for, right?

**Comment by xliiv** [comment]
What chances are to adopt https://github.com/jwilm/alacritty ?
