### ISSUE TITLE
Lack of funding by choice of license

### ISSUE THREAD

**Issue by jhli** [redox-os/redox#573]
**Current: MIT**
**Expected: AGPL3**

ref: http://www.redox-os.org/book/book/introduction/why_redox.html

> Compared to BSD, Linux is completely frontal-lobe-missing, in every imaginable way. The code base is one big, ugly hack, and the design is bad in so many ways. We don't want such a project!

• Logic dictates: If your analysis of Linux as a tech is correct there have to be other reasons that it strives and strives a lot more than BSD. One of those reasons is simply GPL2 vs BSD. BSDs fail cause of their licencse. OSS is aside a few believers financed though companies paying contributers paychecks. MIT/BSD fails here.
• To continue this argument: Linux currently dies cause it is not AGPL3. Where Microsoft (BSD network stack), Apple and others did not give back on MIT projects, Google, Facebook, Amazon et al are not giving back their PaaS mods to Linux because it is not AGPL3.

I can't judge on Rust and I miss an analysis of L4, QNX etc but this project will, unless you understand the very practical implications of MIT/BSD (and GPL2) be missing the train on funding. And: even if you get funding now, it won't last forever where if the project excels at a tech level, with AGPL3, you would.

This is the key drawback BSDs have and selecting AGPL3 over GPL2 could be your key advantage over Linux.

Consider your choices and good luck.

**Comment by Ticki** [comment]
This is a frequently asked question. From the book:

-----

The GPL is good for forcing people who make changes to the source to contribute back. This would be okay if you were developing a program, but never ideal for libraries or operating systems, because the GPL forces any code that even remotely uses or links to the GPL'd source, to become GPL'd.

Since operating systems are such an integrated part of our lives, we want as little restriction as possible. Restrictive licenses are quite a big disadvantage for OS projects. The MIT license opens up a lot of possibilities, which are simply not plausible with, say, the GPL.

The GPL is upstream-centric, the MIT license is downstream-centric. We happen to prioritize downstream more than upstream, since downstream is what really matters: the userbase, the community, the availability.

We wanted to encourage the use, modification, and packaging of Redox in absolutely all realms. Open source should be open, for everyone. There's absolutely no reason for limiting the usage of the software. Therefore, MIT was the license of choice.

**But what if someone "steals" the source code?**

We wouldn't mind if somebody did that. In order to successfully steal a project, you'd have to make some improvements over the upstream version. You can't sell an apple for $2, if another person stands right next to you, giving them away for free. For this reason, making a (potentially proprietary) fork interesting requires putting some time and money into it.

There is nothing wrong with building on top of Redox. You can't unfairly steal a project. That's simply not possible. For a fork to gain interest, you will have to put effort into it no matter what.

Building on top of Redox, whether it gets to upstream or not, is a thing we appreciate.

We like to have a decentralized structure of the project, allowing people to do whatever they want, no matter how they intend to share it.

**Comment by jhli** [comment]
Well, you did not counter my argument about funding.
Did you? You can deem me (and others) to be wrong, but if you are wrong in the end, then you waste your time (and tge countless hours of others).

Just think about it.

**Comment by jhli** [comment]
In other words, if you don't enforce share back from the big players, you will lose agsinst the linux eco system now **and** long term.

**Comment by Ticki** [comment]
Sorry, but I do not have the time nor energy discussing licensing with everybody. We chose MIT, and I described above why. Furthermore, many of the statements you make are simply wrong.

**Comment by Ticki** [comment]
If you prefer AGPL, feel free to fork and sublicense it.

**Comment by genodeftest** [comment]
> The GPL is good for forcing people who make changes to the source to contribute back. This would be okay if you were developing a program, but never ideal for libraries or operating systems, because the GPL forces any code that even remotely uses or links to the GPL'd source, to become GPL'd.

A possible solution would be releasing the API under any non-permissive license while releasing the core components under (A)GPL.

This is what some software is doing with its "GPL + linking exception"

**Comment by Ticki** [comment]
@genodeftest I'm still wondering: _why?_

This only solves half of the problem.

**Comment by nounoursheureux** [comment]
> In other words, if you don't enforce share back from the big players, you will lose against the Linux eco system now and long term.

We are not fighting against the Linux ecosystem. Our goal is **not** to replace Linux.

> Linux currently dies cause it is not AGPL3

Could you explain what you mean by "Linux currently dies" ? It works very well for me.

> even if you get funding now, it won't last forever where if the project excels at a tech level, with AGPL3, you would.

I can only speak for myself, but I don't think we need funding. The contributors are benevolent, they make Redox better because they want to.

**Comment by zetok** [comment]
>If you prefer AGPL, feel free to fork and sublicense it.

Perhaps someone should do just that. Although GPLv3+ is probably better. I'd happily drop at least a few contributions to it. If anyone is interested, please say so :)

I feel that you should read https://www.reddit.com/r/linux/comments/4bhg3b/rusts_redox_os_could_show_linux_a_few_new_tricks/

It would be a shame if Redox failed because of its current license.

**Comment by nounoursheureux** [comment]
> It would be a shame if Redox failed because of its current license.

Could you explain what you mean by *failure* ? **Our goal is not to replace Linux**, our goal is not to become the next big OS. People contribute to Github because they want to, they have their own reasons. If nobody wants to contribute to Redox anymore, then the project will die. There is no failure, there is no success.

**Comment by i3luefire** [comment]
Well licensing should obviously be left up to the people who write the code. MIT/BSD/OTHER permissive licenses allow this. GPL/GPLV3/OTHER copyleft licenses do not leave the choice up to the person writing the code. They require strict obedience to their philosophy/dogma.

**Comment by NobbZ** [comment]
Creating a sublicensed Repo could even produce more trouble... Can the gpl
parts of the fork be backported to the original Repository without getting
into trouble with GPL terms?

i3luefire <notifications@github.com> schrieb am Di., 22. März 2016 18:30:

**Comment by Ticki** [comment]
> Creating a sublicensed Repo could even produce more trouble... Can the gpl parts of the fork be backported to the original Repository without getting into trouble with GPL terms?

We're not interested in maintaining such a repository, we would be fine with other doing so, though.

**Comment by zetok** [comment]
@nounoursheureux
>Could you explain what you mean by failure ?

Well,
>(…) our goal is not to become the next big OS.

that I consider to be a failure. Anything less won't gain enough traction to even stay alive.

With that being said...
>“I'm doing a (free) operating system (just a hobby, won't be big and professional like gnu) for 386(486) AT clones.”

As if I would believe you even for a second. ;)

>If nobody wants to contribute to Redox anymore, then the project will die.

If the current goal is to make Redox die, then I agree that MIT is a perfect choice of license. Could you though please reflect that on website/docs, so that there will be no confusion?

===
@NobbZ 
>Can the gpl parts of the fork be backported to the original Repository without getting into trouble with GPL terms? 

Nope. Unless explicitly dual-licensed under GPL/MIT, which would render licensing it under GPL ~pointless.

**Comment by Ticki** [comment]
> If the current goal is to make Redox die, then I agree that MIT is a perfect choice of license.

Please keep it civil.

> Could you though please reflect that on website/docs, so that there will be no confusion?

See "Will Redox replace Linux?".

**Comment by jackpot51** [comment]
If I may interject:

The major contributors to this project have all agreed with and embraced the MIT license. What right do you have for *demanding* that the code we wrote be relicensed?

If you want to be taken seriously, contribute, push a PR containing something that we actually need, and ask that it be GPL licensed.

**Comment by nounoursheureux** [comment]
> that I consider to be a failure. Anything less won't gain enough traction to even stay alive.

But this project *is* alive.

> >If nobody wants to contribute to Redox anymore, then the project will die.

> If the current goal is to make Redox die, then I agree that MIT is a perfect choice of license. Could you though please reflect that on website/docs, so that there will be no confusion?

Ok, I was not very clear. What I mean is that I prefer to have a small community of people that really care about the project and contribute because it is their choice, than to have lots of developers that really don't give a shit because all they want is to build their product on top of Redox. I prefer that we leave these people do what they want, and hopefully Redox will allow them to build great things, even if they don't want to contribute back.

**Comment by jhli** [comment]
@jackpot51 I don't care.

I offered my advise because the hate of copyleft, the wishes and options of close-source derivates are so strong within the core contribs (obviously) so that you ruin your own project.

Not Linus but the GPL is what made the gnu ecosystem as a base of the linux ecosystem possible. But the gpl2 is lackluster confronted with todays challenges and thus my recommendation to you core contrib guys is the agpl3.

Sure a bunch (CURRENTLY commercially financed or gpl-hating) devs will object. I don't have any problems with you guys ruining your own project / its future I just feel sad to have less great and striving OSS options.

Good luck.

**Comment by zetok** [comment]
@Ticki 
>>If the current goal is to make Redox die, then I agree that MIT is a perfect choice of license.

>Please keep it civil.

Err, which part of it is not civil? Are you seriously considering talking about possible outcomes as not being civil? Really?

>>Could you though please reflect that on website/docs, so that there will be no confusion?

>See "Will Redox replace Linux?".

Yeah, and you are the certified oracle that is able to predict the future 100% accurate all the time.

Well, this only asserts more the "gut feeling" that Redox will die.

===
@jackpot51
>The major contributors to this project have all agreed with and embraced the MIT license. What right do you have for demanding that the code we wrote be relicensed?

I've expressed interest in helping with an OS written in Rust and licensed under GPL. Anything other is a waste of time – could you point though where I've "demanded" from you to stop wasting your time? Your time is yours only - you're free to do with it whatever you want, regardless of me considering it to be a "waste" :)

>If you want to be taken seriously, contribute, push a PR containing something that we actually need, and ask that it be GPL licensed.

Pfff.

What right do you have to demand from me to slave away? As I've stated before, I'm interested in helping Rust OS licensed under GPL. It's up to you to make that happen or not.

I'd treat your proposition seriously if I was proposed money in exchange for slaving away.

===
@nounoursheureux 
>>that I consider to be a failure. Anything less won't gain enough traction to even stay alive.

>But this project is alive.

At this very moment, yes. *So were quite a few other projects*. What you might ponder on, is how well it endure the trial of time, which is the ultimate test.

>>>If nobody wants to contribute to Redox anymore, then the project will die.

>>If the current goal is to make Redox die, then I agree that MIT is a perfect choice of license. Could you though please reflect that on website/docs, so that there will be no confusion?

>Ok, I was not very clear. What I mean is that I prefer to have a small community of people that really care about the project and contribute because it is their choice (…)

Ok, count me as confused – GPL is something that does help to build stronger community that really care about the software they developing. AFACS, it's the opposite with MIT, which would make it harder for you to get the desired community. Not impossible, but harder to do than necessary.

>(…) than to have lots of developers that really don't give a shit because all they want is to build their product on top of Redox.

And this is the kind of abuse that MIT and alike licensed projects do receive. To me, it looks like GPL would fit what you want perfectly, and MIT is the opposite of what you want.

>I prefer that we leave these people do what they want, and hopefully Redox will allow them to build great things, even if they don't want to contribute back.

They can have their way anyway, regardless of the license :D
To not look far away, there are plenty of companies that outright violate GPL on the "western" side.
On the other side, feel free to look at almost every chinese product that uses Linux – they don't give a damn about the license.

**Comment by jackpot51** [comment]
https://www.youtube.com/watch?v=PaKIZ7gJlRU

**Comment by hauleth** [comment]
Personally I see that currently more and more companies are opening their products and contributing to FLOSS because it is cheaper. The cheapest developer is one that you do not need to pay. Of course there are some examples where some BigBadCompany™ "stealed" code and then was distributing it as "their own system", i.e. Apple with BSD, but guess what, after some time Apple found that developing their own, closed-source but FLOSS based kernel is PITA as they now need to pay that one guy which job is just to `git fetch <floss_kernel_repo> && git rebase floss_project/master`. After that enlightenment they just open sourced Darwin.

Also as Sony is using (AFAIK) FreeBSD on their consoles I truly don't believe that they done some magic in kernel and then keep it for themselves. Only if there were some code that was unique for their platform (and due that it would be unnecessary bloat for anyone else) they hasn't pushed it to the upstream.

Other issue is `glibc` magic license. As `libredox` (`libstd` implementation for Redox) is de facto part of the system it would be really unreasonable to use only (A)GPL for that.

To be honest, in modern world, where almost every piece of software relies (more or less) on FLOSS and FLOSS still exist (and they pay them to exist, like OpenSSL, Mozilla, even Linux Foundatione) I find more permissive license like MIT or BSD more suitable and I do not find it harmful for anyone.

But if you want to praise St. Ignucy and meet with your own small GNU-only circle of jerk then I cannot stop you.

---

> I offered my advise because the hate of copyleft

Wait… What? You hate copyleft so you are proposing most copylefty licence available?

> the wishes and options of close-source derivates are so strong within the core contribs

No, we aren't praising for closed source derivatives, but personally I do not believe that they will happen in large scale, as they are infeasible economically.

> Not Linus

I believe so.

> but the GPL is what made the gnu ecosystem as a base of the linux ecosystem possible

To be honest, I think that was marketing and that RMS cannot finish his own kernel since always.

---

After reading all these GNU-activist in this thread I can only paraphrase Linus:

> Quite frankly, even if the choice of MIT were to do *nothing* but keep the GPL programmers out, that in itself would be a huge reason to use MIT.

**PS**: Official name for that license is X11 (guess why). Assuming that you are using GNU/Linux and are writing this posts there I assume that you use `lynx`.

**Comment by nounoursheureux** [comment]
> > (…) than to have lots of developers that really don't give a shit because all they want is to build their product on top of Redox.

> And this is the kind of abuse that MIT and alike licensed projects do receive. To me, it looks like GPL would fit what you want perfectly, and MIT is the opposite of what you want.

My POV is that I want to let people use Redox however they wish. If they want to build a product on top of it without contributing back, then that's fine. If they want to contribute, then that's great ! Anyway, I don't want to force anything on anyone. It is as simple as that.

> They can have their way anyway, regardless of the license :D
To not look far away, there are plenty of companies that outright violate GPL on the "western" side.
On the other side, feel free to look at almost every chinese product that uses Linux – they don't give a damn about the license.

Well, I don't see the point on using a license that we don't enforce

**Comment by Ticki** [comment]
> Err, which part of it is not civil? Are you seriously considering talking about possible outcomes as not being civil? Really?

http://www.redox-os.org/coc/, see 4. and 5.

> Yeah, and you are the certified oracle that is able to predict the future 100% accurate all the time.

What is it that you are unable to understand about "civil"?

> I've expressed interest in helping with an OS written in Rust and licensed under GPL.

Make a fork then! They're welcome.

> What right do you have to demand from me to slave away?

We're simply asking you to contribute before strongly opposing and trying to change our choice of license.

> I'd treat your proposition seriously if I was proposed money in exchange for slaving away.

Stop this stupid behavior.

**Comment by zetok** [comment]
@hauleth
>Other issue is `glibc` magic license. As `libredox` (`libstd` implementation for Redox) is de facto part of the system it would be really unreasonable to use only (A)GPL for that.

Right. There is a reason why LGPL exists though :)

===

@nounoursheureux

>My POV is that I want to let people use Redox however they wish. If they want to build a product on top of it without contributing back, then that's fine. If they want to contribute, then that's great ! Anyway, I don't want to force anything on anyone. It is as simple as that.

That's nice, even if probably somewhat impractical :)

>Well, I don't see the point on using a license that we don't enforce

Ach! :D

What you got there is pretty exclusive club, where people with different opinion than "we" aren't welcome.

I.e. "we" there implies that there's no way someone who has different opinion on the license part could become part of "we". Kinda sad.

===

@Ticki 
>>Err, which part of it is not civil? Are you seriously considering talking about possible outcomes as not being civil? Really?

>http://www.redox-os.org/coc/, see 4. and 5.

Indeed insightful read.

Now, lets get to the point(s).

\4. I respect your opinons on the license matter. Now, with that being said, do you also dare to apply same terms of CoC to yourself and your Redox fellows?

That would make a true massacre among your ranks, considering that from this discussion, (aside from @nounoursheureux, with whom it was nice to discuss) it would seem that you are all assholes that don't even abide their own CoC, @hauleth promptly taking the lead in breaking the rule(s).  Please respect my humble opinion on the matter.

\5. Yes, I did not provide any criticism, merely suggestions that I perceive as improvements to the workflow. And no, I'm not really interested in experimenting. As they say, thanks, but not thanks :)

Which makes me conclude that you've got some nice moves there, hushing people into silence using CoC when their opinon differs from your own, while you yourself absolutely don't care about the "rules".



>>Yeah, and you are the certified oracle that is able to predict the future 100% accurate all the time.

>What is it that you are unable to understand about "civil"?

Oh, sorry, did I offend you by doubting your ability to predict the future? Wait, did I just hear the sound of your whip being used against differing opinion?

https://www.youtube.com/watch?v=IBH97ma9YiI ← I have a feeling that you might find it.. inspirational, so to say.

>>I've expressed interest in helping with an OS written in Rust and licensed under GPL.

>Make a fork then! They're welcome.

Sadly, I don't have enough time to maintain a fork of whole OS. Just enough of it to possibly help with one though ;)

>>I'd treat your proposition seriously if I was proposed money in exchange for slaving away.

>Stop this stupid behavior.

Wow. Good to know that we don't live any longer in times when work is being paid for. Must have missed that moment.

**Comment by Ticki** [comment]
> \4. I respect your opinons on the license matter. Now, with that being said, do you also dare to apply same terms of CoC to yourself and your Redox fellows?

Yes of course.

> hushing people into silence using CoC when their opinon differs from your own

That is not, at all, what I'm saying. I just want, at minimum, a civil discussion.

> Oh, sorry, did I offend you by doubting your ability to predict the future? Wait, did I just hear the sound of your whip being used against differing opinion?

Again, childish behavior. Please stop it.

> Wow. Good to know that we don't live any longer in times when work is being paid for. Must have missed that moment.

No-one is focing you to do anything.

---------

It is fair to disagree, but to participate in Redox, as a community, requires you to follow the code of conduct, which you do not.

**Comment by jackpot51** [comment]
Locking due to circular arguments. The contributors decide the license, and have decided to use MIT.
