### ISSUE TITLE
clock_gettime doesn't always return an updated time

### ISSUE THREAD

**Issue by glegris** [redox-os/redox#575]
**Reproduction**: 
Inside a process, successive calls of clock_gettime gives the same time value, except if sleep is called between the calls. The code below allows to reproduce the 2 behaviors.

1) Compile the test code:
i386-elf-redox-gcc -o time_test time_test.c

2) Test 1 currently fails (simple loop between two calls of clock_gettime) 
time_test 

3) Test 2 (sleep between two clock_gettime calls)
time_test sleep

**Expected behavior**: 

timespec should be updated between successive calls to clock_gettime

I provide the source code below as attachment doesn't work for me (!)
---
# include <stdlib.h>
# include <stdio.h>
# include <dirent.h>
# include <sys/time.h>
# include <time.h>
# include <unistd.h>

int main(int argc, char *\* argv){
    printf("Test %d\n", argc);
    int i;
    for(i = 0; i < argc; i++){
        printf("%d: %s\n", i, argv[i]);
    }

```
struct timespec tp;
clock_gettime(CLOCK_REALTIME, &tp);
int start_time = (int)tp.tv_sec; 
printf("clock_gettime start %d %d\n", (int)tp.tv_sec, (int)tp.tv_nsec);
int a = 64;
if (argc > 1) {
    sleep(2);
} else {
    for(i = 1; i < 100000000; i++){
     a += a / i;
    }
}
clock_gettime(CLOCK_REALTIME, &tp);
printf("clock_gettime end %d %d\n", (int)tp.tv_sec, (int)tp.tv_nsec);
if ((int)tp.tv_sec - start_time < 2) {
    printf("Oops ! time was not updated !\n");
} else {
    printf("OK\n");
}
printf("%i\n", a);    
```

}

**Comment by bglasber** [comment]
I've been taking a look at this because I'm trying to benchmark some system calls...

I think something strange is happening with the way clock interrupts are being handled when a program is executed from the command line. 

If you run:
`fn main() {
   let mut socket = File::create("interrupt:").unwrap();
   let mut c = 0;
   for _ in 1..100000000 { //spin for a while
       c = c+1;
   } 
   let mut socket = File::create("interrupt:").unwrap();
}
`
And check the output of the interrupt scheme, the PIT count is constant, even though the code was executing for while. Further, if you type a whole bunch of stuff in during the loop, the keyboard interrupt count is not increased either.

If you execute the program again after it exits to shell, then the counters increase and reflect what you would expect. 

If you put a sleep in rather than spinning, then the counters also increase.

Perhaps interrupts are being queued until context switches?

I can try and fix this myself but I'm not really sure where to look to get started... Does someone have any pointers?

**Comment by jackpot51** [comment]
This should be fixed in the new kernel
