### ISSUE TITLE
Use PNGs instead of uncompressed BMP images for UI

### ISSUE THREAD

**Issue by archshift** [redox-os/redox#640]
PNGs are smaller, and it's likely that more time will be spent reading bitmaps from the disk than decoding the image from PNGs.

**Comment by ke7ofi** [comment]
Aren't PNGs bitmaps? I did once see a display server that took SVG screenshots...

**Comment by ca1ek** [comment]
bmp::BmpImage would need to be renamed to something more general

**Comment by jackpot51** [comment]
@archshift  This is an issue very important to me, because lossless compression is a huge performance and space benefit. I have added PNG support to the viewer in the latest master, see https://github.com/redox-os/redox/commit/0b371276ce081cfd53e9bee06af1909182592692

As @ca1ek has noted, I have some work to do in orbclient to make image access generic. I will place image support for png and bmp in a new crate, orbimage, which may be used cross-platform. This will allow all programs to load images by file path, without worrying about the underlying image type.

**Comment by jackpot51** [comment]
The big BMP files have been converted and the orbimage library supports PNG and BMP with a generic interface.
