### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by vtomole** [redox-os/redox#831]
This is what I'm getting:http://pastebin.com/QYrmvRTn

**Comment by polymetric1** [comment]
What's your `rustc --version`? I'm getting the same error on 1.16.0. Tried everything listed in the Readme.

**Comment by vtomole** [comment]
rustc 1.7.0

**Comment by bjorn3** [comment]
Thats a too old version. Please update to the latest rust nightly.

**Comment by vtomole** [comment]
using rustc 1.16.0-nightly (7821a9b99 2017-01-23)
http://pastebin.com/WmvF98X0

**Comment by bjorn3** [comment]
You can remove line 4 of `drivers/ahcid/src/main.rs` as workaround.

**Comment by vtomole** [comment]
http://pastebin.com/znKcWUcY

**Comment by polymetric1** [comment]
I've discovered that there are no compile breaking errors on an Ubuntu host with the current revision of redox. I was previously building on Windows and OpenSUSE, both of which get errors. What host system are you building on?

**Comment by chrisfair** [comment]
I am failing build on master under a manjaro system Linux version 4.4.45-1-MANJARO (builduser@manjaro) (gcc version 6.3.1 20170109 (GCC) ) #1 SMP PREEMPT Thu Jan 26 11:32:11 UTC 2017

I get this once I type make all

mkdir -p build/kernel
RUSTC="./krustc.sh" RUSTDOC="./krustdoc.sh" cargo rustc --manifest-path rust/src/libcollections/Cargo.toml --target x86_64-unknown-none --release -- -C soft-float -o build/kernel/libcollections.rlib
error: failed to parse manifest at `/opt/Projects/rust/RustOS/redox/rust/src/librustc_plugin/Cargo.toml`

Caused by:
  expected a value of type `string`, but found a value of type `boolean` for the key `package.build`
make: *** [mk/kernel.mk:3: build/kernel/libcollections.rlib] Error 101


Any ideas ?

**Comment by jackpot51** [comment]
Try again with latest master, please

**Comment by vtomole** [comment]
I'm getting this now: http://pastebin.com/WBcdLmxG

**Comment by jackpot51** [comment]
Are your submodules up to date?

**Comment by vtomole** [comment]
Yeah. I did "git submodule update --recursive --init" multiple times

**Comment by polymetric1** [comment]
What distro are you building on? Just curious, it might be relevant.

**Comment by polymetric1** [comment]
When my build breaks and I haven't made changes, I usually do a full reset. If you've made any changes (please let us know if you have!) make sure you do a `git stash` first. It usually goes as follows:
```sh
$ git pull upstream master

$ rm -rf * # removes all non-hidden files

$ git reset --hard upstream/master

$ make clean # just in case

$ git clean -Xfd # just in case

$ make
```

Also, of course, following the (admittedly still a bit outdated) broken build guide in README.md, remember to regularly update/upgrade your package manager, as well as run `rustup update`. Also, just in case, run `(pkg manager) install make nasm qemu qemu-kvm`. Honestly, this looks like something to do with `rustc` though.
