### ISSUE TITLE
Make the "Orbital Login" window unclusable

### ISSUE THREAD

**Issue by FaraoneLele** [redox-os/redox#859]
The windows named Orbital Login after the boot shows the close button, but it is unclosable: you should remove the top bar or remove the close button
![virtualbox_redox os_26_02_2017_09_26_31](https://cloud.githubusercontent.com/assets/17162630/23338251/b1759cb6-fc05-11e6-9d52-e53121f03369.png)

**Comment by obv-mikhail** [comment]
The login button can be removed as well or made smaller maybe? Looks too long right now.

In terms of eventual login screen design, I think something like on Ubuntu would look good.
[Picture for reference](http://ubuntuguide.net/wp-content/uploads/2013/05/login-screen-without-dots.png).

**Comment by polymetric1** [comment]
I think there should be an option for this "classic" screen. It kind of reminds me of Windows XP.

**Comment by Thetoxicarcade** [comment]
themes!

**Comment by InsidiousMind** [comment]
There are already flags like "Resize" and "Async" which dictate which window options are available, I don't think it would be too much of an issue to add an "Exit" flag and close this issue.

Thing is, orbtk uses `Window::new` from the orbclient rather than `Window::new_flags`. I'm not sure if this is a purposeful design decision which serves an overarching purpose, or something else. This means changing the call to Window::new in orblogin program as well as some changes in the Orbital Scheme and Orbclient.

I have a pull request ready to go that modifies orbtk to use `Window::new_flags` and solves this issue, but i'm not sure if it's worth making the request if it contradicts some design decision I'm not yet aware of.

IMO, normal users should have the ability to pass flags to orbtk to specify resizability, exit, etc.
