### ISSUE TITLE
Proposal: Parse URLs at compile time.

### ISSUE THREAD

**Issue by Ticki** [redox-os/redox#96]
Constantly parsing URLs is an expensive thing to do. I suggest we "compile" urls, for example using a macro. This can convert URLs to a type `Url`, which contains the data for a given url (parsed). This will hopefully improve performance. Thoughts?

**Comment by tedsta** [comment]
What about URLs created at runtime? Like for instance in command arguments.

**Comment by jackpot51** [comment]
I don't think this is totally possible, as the syscalls must pass data that other languages can use, and cannot pass a rust struct.

Can we do a timing test on the current kernel parser?

Could do File::open("none://anything/you/want") to test time

**Comment by Ticki** [comment]
They have to be done on the runtime of course. However, I suggest implementing an URL type (or trait?), as this makes it able to "partly" parse the url (suppose I want to alter the last part of the url).

**Comment by Ticki** [comment]
@jackpot51 Syscalls can't parse structs, but structs can be encoded to binary data, which is more efficient than a string.

**Comment by jackpot51** [comment]
If we had a simple macro that called format!

Like: url!(scheme, path, path, path, path) =? format!("{}:{}/{}/{}/"...

**Comment by jackpot51** [comment]
@Ticki what do you mean? it is encoded minimally already, as utf8. Unless you had a number for each scheme, which, in my opinion, destroys the entire point (a readable, arbitrary division of services). Then each service that wants to define it's own scheme would have to allocate a number for itself (like ports, there would be conflicts)

**Comment by Ticki** [comment]
It will still be readable but will be represented more efficient in the memory, like a compiled programming language.

**Comment by jackpot51** [comment]
And what manner of compilation are you proposing?

This is the URL, if we were to remove the extra // as in #92 
file:some/path/to/file

The path must be present, and must be utf8, as all characters are available for the path
The seperators / and : are only one byte each, and something must be present to indicate the division of path elements.

So, what could be changed other than the scheme? The scheme must be present as full utf8, so that it can be matched against the arbitrary utf8 that drivers and modules are allowed to host.

file is only 4 bytes, replacing it with an int would also be 4 bytes. Schemes could be as short as one byte:
f:some/file/path

How could it be done better?

**Comment by Ticki** [comment]
Okay, I see. It's a crazy - not very throughout thought - idea.

**Comment by Ticki** [comment]
I guess the main issue here is the `//`.

**Comment by Ticki** [comment]
I'll close this issue.

**Comment by jackpot51** [comment]
Thanks, it is a good idea to be as minimal as possible with the URL size, just that your previous PR takes care of that
